### ISSUE TITLE
refreshToken not working

### ISSUE THREAD

**Issue by Coinners** [fariosofernando/run-small-dropbox-package#1]
When calling refreshToken the DropBox Api return this {"error": "invalid_request", "error_description": "The request parameters do not match any of the supported authorization flows. Please refer to the API documentation for the correct parameters."}

**Comment by fariosofernando** [comment]
Oi, Niclas!
Há... caracas... estou tão feliz por realizar esse problema.
Irei ver que problema é esse, e retorno-te

Niclas ***@***.***> escreveu no dia domingo, 5/03/2023 à(s)
22:19:

**Comment by fariosofernando** [comment]
Hi Niclas!
There's... gosh... I'm so glad I did this problem.
I will see what the problem is and get back to you

**Comment by fariosofernando** [comment]
With the new version of the package (v3.0.0), the module responsible for the problem is no longer available.
