### ISSUE TITLE
upload file with non-ascii name

### ISSUE THREAD

**Issue by szuwest** [fariosofernando/run-small-dropbox-package#3]
I have files with non-ASCII characters. 
It will upload failed. 
error：
FormatException: Invalid HTTP header field value.

according to the doc https://www.dropbox.com/developers/reference/json-encoding, it need to do something.
I can't find any work method. Any one can help?
Thanks.

**Comment by fariosofernando** [comment]
Hello,
Can you tell me which method are you using?

**Comment by fariosofernando** [comment]
I was able to replicate your error in my environment. I understood. I resolve this.

![image](https://github.com/fariosofernando/run-small-dropbox-package/assets/75936360/b501e152-48fc-4612-bdf7-376d97c646a8)

**Comment by fariosofernando** [comment]
I added support for non-ASCII characters. Now you can use upload and download operations without worry.

Good luck. Hugs.

![image](https://github.com/fariosofernando/run-small-dropbox-package/assets/75936360/53636138-694d-4fde-aaf2-95b032efcf65)

**Comment by fariosofernando** [comment]
Just update the package:
dependencies:
  run_small_dropbox: ^3.1.0
